server:
  port: 8900
  addr: http://localhost:3000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

my:
  secretKey: test123
spring:
  application:
    name: PAYMENTS-SERVICE
